export * from './alert.constants';
export * from './user.constants';
export * from './movie.constants';
export * from './actor.constants';
export * from './recommendation.constants';
export * from './image.constants';

export const constants = {
    MOVIES_GET_TRENDING_REQUEST: "MOVIES_GET_TRENDING_REQUEST",
    MOVIES_GET_TRENDING_SUCCESS: "MOVIES_GET_TRENDING_SUCCESS",
    MOVIES_GET_TRENDING_FAILURE: "MOVIES_GET_TRENDING_FAILURE",
    MOVIES_RESET: "MOVIES_RESET",
  
    MOVIES_GET_DETAIL_REQUEST: "MOVIES_GET_DETAIL_REQUEST",
    MOVIES_GET_DETAIL_SUCCESS: "MOVIES_GET_DETAIL_SUCCESS",
    MOVIES_GET_DETAIL_FAILURE: "MOVIES_GET_DETAIL_FAILURE",

    MOVIES_GET_ACTORS_REQUEST: "MOVIES_GET_ACTORS_REQUEST",
    MOVIES_GET_ACTORS_SUCCESS: "MOVIES_GET_ACTORS_SUCCESS",
    MOVIES_GET_ACTORS_FAILURE: "MOVIES_GET_ACTORS_FAILURE",

    GENRE_GET_ALL_REQUEST: "GENRE_GET_ALL_REQUEST",
    GENRE_GET_ALL_SUCCESS: "GENRE_GET_ALL_SUCCESS",
    GENRE_GET_ALL_FAILURE: "GENRE_GET_ALL_FAILURE",
  
    SET_SEARCH_TEXT: "SEARCH_SET_SEARCH_TEXT",
  
    SEARCH_REQUEST: "SEARCH_REQUEST",
    SEARCH_SUCCESS: "SEARCH_SUCCESS",
    SEARCH_FAILURE: "SEARCH_FAILURE",
  
    WATCHLIST_GETALL_REQUEST: "WATCHLIST_GETALL_REQUEST",
    WATCHLIST_GETALL_SUCCESS: "WATCHLIST_GETALL_SUCCESS",
    WATCHLIST_GETALL_FAILURE: "WATCHLIST_GETALL_FAILURE",
  
    WATCHLIST_CREATE_REQUEST: "WATCHLIST_CREATE_REQUEST",
    WATCHLIST_CREATE_SUCCESS: "WATCHLIST_CREATE_SUCCESS",
    WATCHLIST_CREATE_FAILURE: "WATCHLIST_CREATE_FAILURE",
  
    WATCHLIST_DELETE_REQUEST: "WATCHLIST_DELETE_REQUEST",
    WATCHLIST_DELETE_SUCCESS: "WATCHLIST_DELETE_SUCCESS",
    WATCHLIST_DELETE_FAILURE: "WATCHLIST_DELETE_FAILURE"
  };
  